feat: a11y updates for expand/collapse elements
department-of-veterans-affairs/swagger-ui pull request #5
Opened 2021-04-08 19:57 UTC by alexandervalencia

### Description

This ticket supports [API-1252](https://vajira.max.gov/browse/API-1252). This updates expand/collapse sections for operations and schemas to have:
- proper indications of state (up arrow/down arrow point the right way when open/close)
- tab-able buttons for keyboard navigation to open/close sections

### Motivation and Context

### How Has This Been Tested?
Tested using VoiceOver for Mac (native software) and Keyboard navigation

### Screenshots (if appropriate):

## Checklist

### My PR contains... 

- [ ] No code changes (`src/` is unmodified: changes to documentation, CI, metadata, etc.)
- [ ] Dependency changes (any modification to dependencies in `package.json`)
- [ ] Bug fixes (non-breaking change which fixes an issue)
- [X] Improvements (misc. changes to existing features)
- [ ] Features (non-breaking change which adds functionality)

### My changes...
- [ ] are breaking changes to a public API (config options, System API, major UI change, etc).
- [ ] are breaking changes to a private API (Redux, component props, utility functions, etc.).
- [ ] are breaking changes to a developer API (npm script behavior changes, new dev system dependencies, etc).
- [X] are not breaking changes.

### Documentation
- [X] My changes do not require a change to the project documentation.
- [ ] My changes require a change to the project documentation.
- [ ] If yes to above: I have updated the documentation accordingly.

### Automated tests
- [X] My changes can not or do not need to be tested.
- [ ] My changes can and should be tested by unit and/or integration tests.
- [ ] If yes to above: I have added tests to cover my changes.
- [ ] If yes to above: I have taken care to cover edge cases in my tests.
- [ ] All new and existing tests passed.

2021-04-12 14:55 UTC, gileswells requested changes
Some failing unit test and a question about arrows.

2021-04-12 14:55 UTC, gileswells commented on src/core/components/model-collapse.jsx
> +        <button aria-expanded={this.state.expanded} className="model-box-control" onClick={this.toggleCollapsed}>
You have some failing unit tests here and it appears like your removal of the `pointer` class is the culprit. The test is searching for that specific class to trigger a click and test expand and collapse but can't find it without the class.

https://github.com/department-of-veterans-affairs/swagger-ui/runs/2324060183?check_suite_focus=true#step:6:1883

Adding a class of `pointer` to the button would sidestep this and fix 2 of the 4 failing tests. It might however be better to update the unit tests though to better target the button itself rather than looking for a `pointer` class that might not even be necessary anymore with the button wrapping everything.

With all the spans being wrapped in a button I think that [this last test](https://github.com/department-of-veterans-affairs/swagger-ui/blob/ft/a11y-updates-for-expand-collapse/test/e2e-cypress/tests/features/model-collapse.js#L50) is going to find itself unnecessary.

2021-04-12 14:55 UTC, gileswells commented on src/core/components/model-collapse.jsx
> +        <button aria-expanded={this.state.expanded} className="model-box-control" onClick={this.toggleCollapsed}>
Something to consider here might also be the impacts on any popular swagger themes that could exist. I wasn't able to find a centralized list of themes to consider testing with.

2021-04-12 14:55 UTC, gileswells commented on src/core/components/models.jsx
> +            <use xlinkHref={showModels ? "#large-arrow-up" : "#large-arrow-down"} />
The change in names of the arrows throws me off. Without anything else to show that the `large-arrow-down` is in fact pointing up in this instance (like a css rotation) and moving the down arrow to the false condition, this change feels confusing to me.

2021-04-12 18:12 UTC, alexandervalencia commented on src/core/components/models.jsx
> +            <use xlinkHref={showModels ? "#large-arrow-up" : "#large-arrow-down"} />
It's not that the icons just changed names... I added a separate svg for an arrow pointing up. 
Previously the collapsed / expanded states were like this:
Collapsed: ▶️
Expanded: 🔽 

Now the states are
Collapsed: 🔽
Expanded: 🔼 

Per my conversation with @brentschnieder, the icons should indicate the intent of the action... in this case, clicking on the button will move content in the direction indicated. If the content needs to come down (expand) the button should show a down-arrow. Clicking on the button changes the icon to an up arrow, indicating that clicking it will move the content back up (collapse). Previously, the icons had no meaningful indication to fulfill a11y requirements

See screenshots for visual details.

![Screen Shot 2021-04-12 at 1 03 14 PM](https://user-images.githubusercontent.com/22045453/114440534-dd475400-9b8f-11eb-97e8-d3efbc719b80.png)
![Screen Shot 2021-04-12 at 1 03 23 PM](https://user-images.githubusercontent.com/22045453/114440535-dddfea80-9b8f-11eb-928e-daf15e328d4c.png)

2021-04-12 18:41 UTC, alexandervalencia commented on src/core/components/model-collapse.jsx
> +        <button aria-expanded={this.state.expanded} className="model-box-control" onClick={this.toggleCollapsed}>
The class being used in some themes to control the title was something I hadn't considered, thanks! I added back to the span where the title is being displayed

2021-04-13 15:25 UTC, gileswells approved these changes
LGTM

2021-04-14 15:23 UTC, merged